.TH AT_EXTRA 4 2026-03-31 Lustre "Lustre Kernel Interfaces"
.SH NAME
at_extra \- how many extra seconds to extend RPC timeout under load
.SH SYNOPSIS
.SY
.BI "lctl get_param at_extra"
.SY
.BI "lctl set_param at_extra=" EXTRA_SECONDS
.YS
.SS PROPERTIES
.TP
.B Access Permissions
.br
.BR 644 " | " -rw-r--r--
.TP
.B Scope
.br
Global
.TP
.br
.B Config
.br
Always present
.TP
.B Default
.br
.RB at_extra= 30
.TP
.B Valid Range
.br
.RB at_extra= 5
.br
.RB at_extra= at_max
.SH DESCRIPTION
.B at_extra
is the incremental number of seconds that a server requests to extend the
RPC timeout for a request the service queue that is about to time out.
The server does not know how much time the RPC will take to complete,
so the client will extend the RPC timeout by
.I EXTRA_SECONDS
each time it gets an early reply on an RPC.
The default provides a balance between sending too many
early replies for the same RPC and overestimating the actual completion time.
.PP
When a server finds a queued request about to time out and needs to send an
early reply out, the server adds the at_extra value. If the time expires,
the Lustre server drops the request, and the client enters recovery status and
reconnects to restore the connection to normal status.
.PP
If you see multiple early replies for the same RPC asking for 30-second
increases, change at_extra to a larger number to cut down on early replies sent
and, therefore, network load.
.SH MODULES
This parameter is in the following modules:
.EX
.B at_extra
.EE
.SH EXAMPLES
If there are many early replies,
increase the extra margin to 15s for all nodes in the filesystem:
.EX
.RB mgs# " lctl set_param -P at_extra=15"
.EE
.SH AVAILABILITY
.B at_extra
is part of the
.BR lustre (7)
filesystem package since release 1.6.4.
.\" commit 1.6.0-1416-gde3c3fdf25
.SH SEE ALSO
.BR at_early_margin (4),
.BR at_history (4),
.BR at_max (4),
.BR at_min (4),
.BR ldlm_enqueue_min (4)
