.TH LFS-MIRROR-DELETE 1 2026-08-05 Lustre "Lustre User Utilities"
.SH NAME
lfs-mirror-delete \- delete a specified mirror from an existing mirrored file
.SH SYNOPSIS
.SY "lfs mirror delete"
.RB { --mirror-id
.I MIRROR_ID
|
.BR --component-id | --comp-id | -I
.I COMP_ID
|
.B --pool
.IR POOL }
.RB [ --no-warn ]
.I MIRRORED_FILE
.YS
.SH DESCRIPTION
This command deletes a mirror with mirror ID
.I MIRROR_ID
or containing a component with
.I COMP_ID
or containing a component on
.I POOL
out of a mirrored file specified by the path name
.IR MIRRORED_FILE .
.P
If
.I MIRRORED_FILE
has only one mirror existing after split,
it will be converted to a regular non-mirrored file.
.P
If the deleted mirror is a data mirror that has an associated erasure coding
(EC) parity mirror, the MDS deletes the parity mirror along with the data
mirror in a single operation. Deleting the last data mirror is refused, since
a file left holding parity mirrors alone cannot be read. When deleting a
parity mirror directly, a warning is printed when it takes away the last
redundant copy of the file, since the data mirror it protected is then left
alone. No warning is printed while another data mirror remains, and
.B --no-warn
suppresses it entirely.
.P
If the original
.I MIRRORED_FILE
is not a mirrored file, then the command will return an error.
.SH OPTIONS
.TP
.B --no-warn
Do not print the warning issued when the operation removes the last redundant
copy of the file.
.TP
.BI --mirror-id " MIRROR_ID"
The numerical unique identifier for a mirror. The mirror ID is unique within a
mirrored file and is automatically assigned at file creation or extension time.
It can be fetched by
.B lfs getstripe
command (see
.BR lfs (1)).
.TP
.BR -I ", " --comp-id " \fICOMP_ID"
The numerical unique identifier for a component contained within a mirror.
.TP
.BI --pool " POOL"
The pool storing a component contained within a mirror.
.SH EXAMPLES
Delete the mirror with ID 2 of /mnt/lustre/file1:
.RS
.EX
.B # lfs mirror delete --mirror-id 2 /mnt/lustre/file1
.EE
.RE
.PP
Delete the mirror containing the component with ID 65537 of /mnt/lustre/file1:
.RS
.EX
.B # lfs mirror delete --comp-id 65537 /mnt/lustre/file1
.EE
.RE
.PP
Split a mirror on pool ssd out of /mnt/lustre/file1 and destroy it:
.RS
.EX
.B # lfs mirror delete --pool ssd /mnt/lustre/file1
.EE
.RE
.PP
Delete the data mirror with ID 1 out of an EC mirrored file that has another
data mirror as well. Its associated parity mirror is deleted along with it:
.RS
.EX
.B # lfs mirror delete --mirror-id 1 /mnt/lustre/ecfile
.EE
.RE
.SH AVAILABILITY
The
.B lfs mirror delete
command is part of the
.BR lustre (7)
filesystem package since release 2.13.0
.\" Added in commit v2_12_58-138-g6d0e247cfc
.SH SEE ALSO
.BR lfs (1),
.BR lfs-mirror-create (1),
.BR lfs-mirror-extend (1),
.BR lfs-mirror-resync (1),
.BR lfs-mirror-split (1),
.BR lfs-mirror-verify (1),
.BR lfs-setstripe (1)
