// Copyright 2023 Hewlett Packard Enterprise Development LP

@Library('dst-shared@master') _

pipeline {
    agent {
        node { label 'Centos8_nodes' }
    }

    environment {
        // Needed by signArtifacts for correct location of buildlog.logs in Artifactory:
        PRODUCT = "neo"
        BRANCH_NAME = "release"
        TARGET_OS = "hpc-lus-filesystem"
        TARGET_ARCH = "noarch"
    }

    options {
        // Don't fill up the build server with unnecessary cruft
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {
        stage('Changes Notes') {
           steps {
                sh "/bin/bash -x /build/bin/build_changesnotesv5_cloudbees.sh"
            }
        }

        stage('Build RPMs') {
            steps {
                sh "umask 022"
                sh "/bin/bash -x contrib/jenkins/build_phase2.sh"
            }
        }

        stage('Scan/Sign RPMs') {
            steps {
                signArtifacts([artifacts: 'rpmbuild/'])
            }
        }

        stage('Store RPMs') {
            steps {
                sh "contrib/jenkins/store-RPMs.sh"
            }
        }
    }
    post {
        success {
            script {
                if ( checkFileExists(filePath: 'packages.txt') ) {
                    archiveArtifacts artifacts: 'packages.txt, rpmbuild/*.log, LUSTRE-VERSION-FILE', fingerprint: false
                } else {
                    println "packages.txt not found"
                }
            }
        }
        failure {
            emailext body: "See ${env.BUILD_URL}",
                     to: "${env.RE_Alert}",
                     from: "${env.GP_MAILTARGET}",
                     subject: "Build failed in CI: ${env.JOB_NAME} #${env.BUILD_NUMBER}"
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    emailext body: "See ${env.BUILD_URL}",
                             to: "${env.RE_Alert}",
                             from: "${env.GP_MAILTARGET}",
                             subject: "Jenkins build is back to normal : ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                }
            }
        }
    }
}
