// Copyright 2023 Hewlett Packard Enterprise Development LP

@Library('dst-shared@master') _

pipeline {
    agent {
        node { label 'Centos8_nodes' }
    }

    environment {
        // These parameters should remain static for the ORNL6.2_Lustre job:
        JP_REPO = 'lustre'
        JP_NEO_RELEASE = 'ORNL6.2'

        // These dynamic parameters are defined in the ORNL6.2_Lustre job:
        //   JP_VERSION = '2.15'
        //   JP_VERS_TAG = 'x6.2t'
        //   JP_IEM_BRANCH = 'cs_6.x-int'
        //   JP_OBSOLETES = '2.7.19.8.x8-248_3.10'
        //   JP_SPECIAL_BUILD = ''
        //   JP_INTEGRATION_BUILD = 'TRUE'
        //   JP_PACKAGE_NAME = 'lustre_ib'
        //   JP_FS_BACKEND = 'both'
        //   JP_KFI = '/usr/src/kfabric-0.1.0/default'
        //   JP_TARGET_KERNEL = ''
    }

    options {
        // Don't fill up the build server with unnecessary cruft
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {
        stage('Changes Notes') {
           steps {
                sh "/bin/bash -x /build/bin/build_changesnotesv5_cloudbees.sh"
            }
        }

        stage('Build RPMs') {
            steps {
                sh "umask 022"
                sh "/bin/bash -x contrib/jenkins/build_phase2.sh"
            }
        }

        stage('Scan/Sign RPMs') {
            steps {
                signArtifacts([artifacts: 'rpmbuild/'])
            }
        }

        stage('Store RPMs') {
            steps {
                sh "contrib/jenkins/store-RPMs.sh"
            }
        }
    }
    post {
        success {
            script {
                if ( checkFileExists(filePath: 'packages.txt') ) {
                    archiveArtifacts artifacts: 'packages.txt, rpmbuild/*.log, LUSTRE-VERSION-FILE', fingerprint: false
                } else {
                    println "packages.txt not found"
                }
            }
        }
        failure {
            emailext body: "See ${env.BUILD_URL}",
                     to: "${env.RE_Alert}",
                     from: "${env.GP_MAILTARGET}",
                     subject: "Build failed in CI: ${env.JOB_NAME} #${env.BUILD_NUMBER}"
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    emailext body: "See ${env.BUILD_URL}",
                             to: "${env.RE_Alert}",
                             from: "${env.GP_MAILTARGET}",
                             subject: "Jenkins build is back to normal : ${env.JOB_NAME} #${env.BUILD_NUMBER}"
                }
            }
        }
    }
}
