/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Enable BGL Features */
/* #undef BGL_SUPPORT */

/* disable libcfs CDEBUG, CWARN */
#define CDEBUG_ENABLED 1

/* disable libcfs ENTRY/EXIT */
#define CDEBUG_ENTRY_EXIT 1

/* build ldiskfs as a module */
#define CONFIG_LDISKFS_FS_MODULE 1

/* enable posix acls for ldiskfs */
#define CONFIG_LDISKFS_FS_POSIX_ACL 1

/* enable fs security for ldiskfs */
#define CONFIG_LDISKFS_FS_SECURITY 1

/* enable extended attributes for ldiskfs */
#define CONFIG_LDISKFS_FS_XATTR 1

/* this kernel contains Red Hat 2.4.20 patches */
#define CONFIG_RH_2_4_20 1

/* kernel has cpu affinity support */
#define CPU_AFFINITY 1

/* Enable DMU OSD */
/* #undef DMU_OSD */

/* do data checksums */
/* #undef ENABLE_CHECKSUM */

/* Liblustre Can Recover */
#define ENABLE_LIBLUSTRE_RECOVERY 1

/* Use the Pinger */
#define ENABLE_PINGER 1

/* register_sysctl_table want 2 args */
#define HAVE_2ARGS_REGISTER_SYSCTL 1

/* INIT_WORK use 3 args and store data inside */
#define HAVE_3ARGS_INIT_WORK 1

/* support alder32 checksum type */
#define HAVE_ADLER 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <asm/page.h> header file. */
#define HAVE_ASM_PAGE_H 1

/* Define to 1 if you have the <asm/types.h> header file. */
#define HAVE_ASM_TYPES_H 1

/* panic_notifier_list is atomic_notifier_head */
/* #undef HAVE_ATOMIC_PANIC_NOTIFIER */

/* Enable adaptive timeouts support */
/* #undef HAVE_AT_SUPPORT */

/* Kernel has bit_spinlock.h */
#define HAVE_BIT_SPINLOCK_H 1

/* Define to 1 if you have the <blkid/blkid.h> header file. */
#define HAVE_BLKID_BLKID_H 1

/* kernel expects return from shrink_cache */
/* #undef HAVE_CACHE_RETURN_INT */

/* call_rcu takes three parameters */
/* #undef HAVE_CALL_RCU_PARAM */

/* kernel has cancel_dirty_page instead of clear_page_dirty */
/* #undef HAVE_CANCEL_DIRTY_PAGE */

/* kernel has third arg can_sleep in fs/locks.c: flock_lock_file_wait() */
/* #undef HAVE_CAN_SLEEP_ARG */

/* Define to 1 if you have the <catamount/data.h> header file. */
/* #undef HAVE_CATAMOUNT_DATA_H */

/* cond_resched found */
#define HAVE_COND_RESCHED 1

/* Define to 1 if you have the `connect' function. */
#define HAVE_CONNECT 1

/* inode_operations->follow_link returns a cookie */
#define HAVE_COOKIE_FOLLOW_LINK 1

/* cpumask_t found */
#define HAVE_CPUMASK_T 1

/* cpu_online found */
#define HAVE_CPU_ONLINE 1

/* kernel has new dev_set_rdonly */
#define HAVE_DEV_SET_RDONLY 1

/* the kernel passes struct file to direct_IO */
/* #undef HAVE_DIO_FILE */

/* after 2.6.17 dquote use mutex instead if semaphore */
/* #undef HAVE_DQUOTOFF_MUTEX */

/* Kernel has d_add_unique */
#define HAVE_D_ADD_UNIQUE 1

/* d_move_locked is exported by the kernel */
#define HAVE_D_MOVE_LOCKED 1

/* d_rehash_cond is exported by the kernel */
#define HAVE_D_REHASH_COND 1

/* Define to 1 if you have the <endian.h> header file. */
#define HAVE_ENDIAN_H 1

/* kernel exports __iget */
/* #undef HAVE_EXPORT___IGET */

/* Define to 1 if you have the <ext2fs/ext2fs.h> header file. */
#define HAVE_EXT2FS_EXT2FS_H 1

/* filemap_fdatawrite() found */
#define HAVE_FILEMAP_FDATAWRITE 1

/* Kernel exports filemap_populate */
#define HAVE_FILEMAP_POPULATE 1

/* Define to 1 if you have the <file.h> header file. */
/* #undef HAVE_FILE_H */

/* struct open_intent has a file field */
#define HAVE_FILE_IN_STRUCT_INTENT 1

/* use fops->readv */
#define HAVE_FILE_READV 1

/* use fops->writev */
#define HAVE_FILE_WRITEV 1

/* struct file_operations has flock field */
#define HAVE_F_OP_FLOCK 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `get_preemption_level' function. */
/* #undef HAVE_GET_PREEMPTION_LEVEL */

/* gfp_t found */
#define HAVE_GFP_T 1

/* kernel has grab_cache_page_nowait_gfp() */
/* #undef HAVE_GRAB_CACHE_PAGE_NOWAIT_GFP */

/* Define to 1 if you have the `inet_ntoa' function. */
#define HAVE_INET_NTOA 1

/* struct inode has i_blksize field */
#define HAVE_INODE_BLKSIZE 1

/* after 2.6.15 inode have i_mutex intead of i_sem */
#define HAVE_INODE_I_MUTEX 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if return type of invalidatepage should be int */
#define HAVE_INVALIDATEPAGE_RETURN_INT 1

/* invalidate_bdev has second argument */
#define HAVE_INVALIDATE_BDEV_2ARG 1

/* struct inode has i_alloc_sem */
#define HAVE_I_ALLOC_SEM 1

/* kernel has .slice_read */
/* #undef HAVE_KERNEL_SPLICE_READ */

/* struct kiobuf has a dovary field */
/* #undef HAVE_KIOBUF_DOVARY */

/* kernel has struct kmem_cache */
#define HAVE_KMEM_CACHE 1

/* kmem_cache_create has dtor argument */
#define HAVE_KMEM_CACHE_CREATE_DTOR 1

/* kmem_cache_destroy(cachep) return int */
#define HAVE_KMEM_CACHE_DESTROY_INT 1

/* use libcap */
/* #undef HAVE_LIBCAP */

/* libefence support is requested */
/* #undef HAVE_LIBEFENCE */

/* use libpthread */
#define HAVE_LIBPTHREAD 1

/* readline library is available */
/* #undef HAVE_LIBREADLINE */

/* libwrap support is requested */
/* #undef HAVE_LIBWRAP */

/* Define to 1 if you have the <linux/exportfs.h> header file. */
/* #undef HAVE_LINUX_EXPORTFS_H */

/* Define to 1 if you have the <linux/fs.h> header file. */
#define HAVE_LINUX_FS_H 1

/* linux/posix_acl_xattr.h found */
#define HAVE_LINUX_POSIX_ACL_XATTR_H 1

/* Define to 1 if you have the <linux/quota.h> header file. */
#define HAVE_LINUX_QUOTA_H 1

/* Define to 1 if you have the <linux/random.h> header file. */
#define HAVE_LINUX_RANDOM_H 1

/* Define to 1 if you have the <linux/types.h> header file. */
#define HAVE_LINUX_TYPES_H 1

/* Define to 1 if you have the <linux/unistd.h> header file. */
#define HAVE_LINUX_UNISTD_H 1

/* Define to 1 if you have the <linux/version.h> header file. */
#define HAVE_LINUX_VERSION_H 1

/* Enable lru resize support */
/* #undef HAVE_LRU_RESIZE_SUPPORT */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* mm_inline found */
/* #undef HAVE_MM_INLINE */

/* kernel has MS_FLOCK_LOCK flag */
/* #undef HAVE_MS_FLOCK_LOCK */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* node_to_cpumask is exported by the kernel */
#define HAVE_NODE_TO_CPUMASK 1

/* is kernel export nr_pagecache */
#define HAVE_NR_PAGECACHE 1

/* does kernel have PageChecked and SetPageChecked */
#define HAVE_PAGE_CHECKED 1

/* kernel have PageConstant supported */
/* #undef HAVE_PAGE_CONSTANT */

/* struct page has a list field */
/* #undef HAVE_PAGE_LIST */

/* page_mapped found */
#define HAVE_PAGE_MAPPED 1

/* the kernel defines PDE */
#define HAVE_PDE 1

/* is kernel have PG_fs_misc */
/* #undef HAVE_PG_FS_MISC */

/* readlink returns ssize_t */
#define HAVE_POSIX_1003_READLINK 1

/* have quota64 */
#define HAVE_QUOTA64 1

/* Enable quota support */
#define HAVE_QUOTA_SUPPORT 1

/* have RCU defined */
#define HAVE_RCU 1

/* register_cache found */
/* #undef HAVE_REGISTER_CACHE */

/* SLES10 SP2 use extra parameter in vfs */
#define HAVE_SECURITY_PLUG 1

/* set_fs_pwd is exported */
#define HAVE_SET_FS_PWD 1

/* show_task is exported */
#define HAVE_SHOW_TASK 1

/* size_t is long type */
#define HAVE_SIZE_T_LONG 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* spinlock_t is defined */
#define HAVE_SPINLOCK_T 1

/* ssize_t is long type */
#define HAVE_SSIZE_T_LONG 1

/* first parameter of vfs_statfs is dentry */
#define HAVE_STATFS_DENTRY_PARAM 1

/* struct statfs has a namelen field */
#define HAVE_STATFS_NAMELEN 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strnlen' function. */
#define HAVE_STRNLEN 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/user.h> header file. */
#define HAVE_SYS_USER_H 1

/* Define to 1 if you have the <sys/vfs.h> header file. */
#define HAVE_SYS_VFS_H 1

/* tasklist_lock exported */
#define HAVE_TASKLIST_LOCK 1

/* task p_pptr found */
/* #undef HAVE_TASK_PPTR */

/* kernel export truncate_complete_page */
/* #undef HAVE_TRUNCATE_COMPLETE_PAGE */

/* __u64 is long long type */
#define HAVE_U64_LONG_LONG 1

/* Define umount_begin need second argument */
/* #undef HAVE_UMOUNTBEGIN_VFSMOUNT */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* struct file_operations has an unlock ed_ioctl field */
#define HAVE_UNLOCKED_IOCTL 1

/* unregister_blkdev return int */
#define HAVE_UNREGISTER_BLKDEV_RETURN_INT 1

/* VFS intent patches are applied */
/* #undef HAVE_VFS_INTENT_PATCHES */

/* vfs_kern_mount exist in kernel */
/* #undef HAVE_VFS_KERN_MOUNT */

/* if vfs_readdir need 64bit inode number */
/* #undef HAVE_VFS_READDIR_U64_INO */

/* Kernel has xattr_acl */
/* #undef HAVE_XATTR_ACL */

/* Define to 1 if you have the <xtio.h> header file. */
/* #undef HAVE_XTIO_H */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* __d_move is exported by the kernel */
/* #undef HAVE___D_MOVE */

/* __d_rehash is exported by the kernel */
/* #undef HAVE___D_REHASH */

/* OFED version */
#define IBLND_OFED_VERSION 1025

/* call sysio init functions */
#define INIT_SYSIO 1

/* quota_read found */
#define KERNEL_SUPPORTS_QUOTA_READ 1

/* enable libcfs LASSERT, LASSERTF */
#define LIBCFS_DEBUG 1

/* Liblustre Support ACL-enabled MDS */
#define LIBLUSTRE_POSIX_ACL 1

/* use /dev/urandom for random data */
#define LIBLUSTRE_USE_URANDOM 1

/* use dumplog on panic */
/* #undef LNET_DUMP_ON_PANIC */

/* Max LNET payload */
#define LNET_MAX_PAYLOAD LNET_MTU

/* Multi-threaded user-level lustre port */
/* #undef LUSTRE_ULEVEL_MT */

/* Report minimum OST free space */
/* #undef MIN_DF */

/* IOCTL Buffer Size */
#define OBD_MAX_IOCTL_BUFFER 16384

/* Name of package */
#define PACKAGE "lustre"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://bugzilla.lustre.org/"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Lustre"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Lustre LUSTRE_VERSION"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lustre"

/* Define to the version of this package. */
#define PACKAGE_VERSION "LUSTRE_VERSION"

/* Enable POSIX OSD */
/* #undef POSIX_OSD */

/* enable randomly alloc failure */
#define RANDOM_FAIL_ALLOC 1

/* The size of a `unsigned long long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG_LONG 8

/* use tunable backoff TCP */
/* #undef SOCKNAL_BACKOFF */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Enable user-level OSS */
/* #undef UOSS_SUPPORT */

/* Write when Checking Health */
/* #undef USE_HEALTH_CHECK_WRITE */

/* Version number of package */
#define VERSION "2.4"

/* zap_page_range with vma parameter */
#define ZAP_PAGE_RANGE_VMA 1
